import {
  AboutCard,
  ExperienceCard,
  ProjectCard,
  ChatCard,
  WalletSection,
} from "./types";

export const aboutCard: AboutCard = {
  id: "about-me",
  type: "about",
  section: "about",
  colors: { light: "#dbeafe", dark: "#1e40af" },
  name: "Jacob Fu",
  avatar: "/headshot.jpg",
  education: {
    school: "University of Waterloo",
    program: "Open to Internship Opportunities",
    logo: "/companies/waterloo.png",
  },
  status: "UWaterloo Computer Science",
  interests: ["Infrastructure", "Distributed Systems", "Building Products"],
  personalFacts: [
    "Hey! I'm Jacob, a CS student at the University of Waterloo. When I'm not coding, you'll probably find me on the volleyball or badminton court (fair warning: I'm pretty terrible at both, but that doesn't stop me).",
    "I went through a few career identity crises before landing on software—first I wanted to be a civil engineer, then an optometrist. Now I just build things on the internet.",
    "Outside of tech, I'm a huge movie and anime fan. Parasite is my all-time favorite film, and Naruto holds a special place in my heart (we don't talk about Boruto though).",
  ],
  calendarLink: "https://calendar.app.google/QCosZGTnWDNeiCuz6",
  socials: {
    linkedin: "https://www.linkedin.com/in/fujacob/",
    github: "https://github.com/fujacob/",
    twitter: "https://x.com/fujacobb/",
    email: "jjacobfu@gmail.com",
  },
};

export const experiences: ExperienceCard[] = [
  {
    id: "exp-hubspot-2",
    type: "experience",
    section: "experiences",
    company: "HubSpot",
    logo: "/companies/hubspot.png",
    role: "Software Engineering Intern (AI-Editor Platform)",
    period: "Winter 2026",
    description: "I'm on the AI-Editor Platform team building HubSpot's next-gen Content Editor. My work focuses on real-time layout generation that lets marketers create modules using natural language prompts.\n\nI built a keyboard-driven interaction layer using Redux middleware to handle module state replication. This reduced content assembly time by 30% for beta users.",
    bullets: [],
    colors: { light: "#ffedd5", dark: "#ea580c" },
    media: { type: "image", src: "/inner-content/content-editor.png", caption: "AI-powered Content Editor interface" },
  },
  {
    id: "exp-kaimz",
    type: "experience",
    section: "experiences",
    company: "Kaimz Inc",
    logo: "/companies/kaimz.png",
    role: "Software Engineering Intern (Security Platform)",
    period: "Fall 2025",
    description: "Built a security monitoring agent in Go that collects system logs and network events from 20+ devices in real-time. The system uses JWT auth, REST APIs, and stores data in AWS S3.\n\nI also developed a RAG-based chatbot for querying historical security events, helping analysts investigate incidents 70% faster through natural language.",
    bullets: [],
    colors: { light: "#ede9fe", dark: "#7c3aed" },
  },
  {
    id: "exp-hubspot-1",
    type: "experience",
    section: "experiences",
    company: "HubSpot",
    logo: "/companies/hubspot.png",
    role: "Software Engineering Intern (Sales Workspace)",
    period: "Summer 2025",
    description: "Shipped HubSpot's next-gen Sales Workspace used by 200k+ daily active sales reps. I improved page load times by 12% through lazy loading and GraphQL caching strategies.\n\nI also resolved 45+ support tickets and architected efficient data-fetching patterns that reduced payload sizes by 35%.",
    bullets: [],
    colors: { light: "#ffedd5", dark: "#ea580c" },
    media: { type: "image", src: "/inner-content/sales-workspace.png", caption: "Sales Workspace dashboard" },
  },
  {
    id: "exp-bridgewell",
    type: "experience",
    section: "experiences",
    company: "Bridgewell Financial",
    logo: "/companies/bridgewell.png",
    role: "Software Engineering Intern (Client Onboarding)",
    period: "Winter 2025",
    description: "Built RESTful APIs for document upload and validation workflows, accelerating client onboarding by 35% and cutting manual processing by 15+ hours per week.\n\nI also implemented an automated email scheduler for follow-up reminders that improved document completion rates by 28%.",
    bullets: [],
    colors: { light: "#e0f2fe", dark: "#0284c7" },
    media: { type: "image", src: "/inner-content/bridgewell.png", caption: "Client onboarding dashboard" },
  },
];

export const projects: ProjectCard[] = [
  {
    id: "proj-pickle",
    type: "project",
    section: "projects",
    title: "Pickle",
    tagline: "AI Streamer Companion",
    image: "/projects/pickle.jpg",
    description: "A real-time AI companion for Twitch streamers that can listen, watch, and talk back. It fuses chat messages, voice, and screen vision into one conversational AI co-host.\n\nBuilt with FastAPI and Electron/React, featuring a hybrid RAG memory system for coherent multi-turn conversations with just 1.5s latency.",
    technologies: [],
    bullets: [],
    githubUrl: "https://github.com/FuJacob/nexhacks",
    devpostUrl: "https://devpost.com/software/pickle-0faw9d",
    colors: { light: "#dcfce7", dark: "#16a34a" },
    media: { type: "youtube", src: "YOBwplgd4hc", caption: "Pickle demo at NexHacks" },
  },
  {
    id: "proj-rbveal",
    type: "project",
    section: "projects",
    title: "RBveal",
    tagline: "Phishing Simulator",
    image: "/projects/rbveal.png",
    description: "A multi-stage phishing simulator that demonstrates how modern scam attacks work. Won RBC's 1st Place Prize ($1,000) among 550+ competitors at UofTHacks 2025.\n\nI built the scammer-call agent using WebSockets, Deepgram, and Twilio, achieving real-time voice conversations with under 1.2s latency.",
    award: "UofTHacks Winner – RBC 1st Place Prize ($1,000)",
    technologies: [],
    bullets: [],
    githubUrl: "https://github.com/FuJacob/rbveal",
    colors: { light: "#f3e8ff", dark: "#9333ea" },
    media: { type: "youtube", src: "v8duvEudLiU", caption: "RBveal demo at UofTHacks" },
  },
  {
    id: "proj-fairfi",
    type: "project",
    section: "projects",
    title: "FairFi",
    tagline: "Call-Agent Bias Detection",
    image: "/projects/fairfi.jpg",
    description: "Detects bias in financial service call agents in real-time. Won P&G's 1st Place Prize ($750) among 640+ competitors at DeltaHacks 2025.\n\nBuilt with Twilio and Cohere for real-time voice analysis, storing interaction data in MongoDB for bias pattern detection.",
    award: "DeltaHacks Winner – P&G 1st Place ($750)",
    technologies: [],
    bullets: [],
    githubUrl: "https://github.com/fujacob/fairfi",
    devpostUrl: "https://devpost.com/software/fairfi",
    colors: { light: "#ffedd5", dark: "#ea580c" },
  },
  {
    id: "proj-metroapocalypse",
    type: "project",
    section: "projects",
    title: "Metro Apocalypse",
    tagline: "Zombie Tag .IO Game",
    image: "/projects/metroapocalypse.png",
    description: "A multiplayer zombie tag .io game built with the Modd.io HTML5 engine. Grew to 248K+ unique users with 4.2M+ play sessions.\n\nMonetized through Patreon and in-game microtransactions, generating $2,500+ CAD in revenue.",
    technologies: [],
    bullets: [],
    liveUrl: "https://www.patreon.com/amuletio",
    colors: { light: "#ecfccb", dark: "#65a30d" },
    media: { type: "image", src: "/inner-content/metro-apocalypse.png", caption: "Metro Apocalypse gameplay" },
  },
  {
    id: "proj-uwshuffle",
    type: "project",
    section: "projects",
    title: "UW Shuffle",
    tagline: "Course Scheduler",
    image: "/projects/uwshuffle.png",
    description: "A course scheduling tool for University of Waterloo students. Helps students find optimal class schedules by shuffling through all possible combinations.\n\nBuilt with Next.js and deployed at uwshuffle.com. Used by hundreds of students each term.",
    technologies: [],
    bullets: [],
    liveUrl: "https://uwshuffle.com",
    colors: { light: "#fef3c7", dark: "#d97706" },
    media: { type: "youtube", src: "TtSnpr8bm3E", caption: "UW Shuffle demo" },
  },
];

export const chatCard: ChatCard = {
  id: "chat-me",
  type: "chat",
  section: "chat",
  title: "Chat with me",
  subtitle: "Ask me anything about my experience",
  colors: { light: "#e0e7ff", dark: "#4f46e5" },
};

export const walletSections: WalletSection[] = [
  { id: "about", label: "About", cards: [aboutCard] },
  { id: "experiences", label: "Experience", cards: experiences },
  { id: "projects", label: "Projects", cards: projects },
  { id: "chat", label: "Chat", cards: [chatCard] },
];
