import {
  AboutCard,
  ExperienceCard,
  ProjectCard,
  WalletSection,
} from "./types";

export const aboutCard: AboutCard = {
  id: "about-me",
  type: "about",
  section: "about",
  colors: { light: "#dbeafe", dark: "#1e40af" },
  name: "Jacob Fu",
  avatar: "/headshot.jpg",
  education: {
    school: "University of Waterloo",
    program: "Computer Science & Finance",
    logo: "/companies/waterloo.png",
  },
  status: "Incoming SWE Intern @ HubSpot",
  interests: ["Infrastructure", "Distributed Systems", "Building Products"],
  personalFacts: [
    "Former aspiring civil engineer, then optometrist",
    "Love volleyball and badminton (even though I suck)",
    "Favourite movie: Parasite",
    "Favourite anime: Naruto (not Boruto)",
  ],
  calendarLink: "https://calendar.app.google/QCosZGTnWDNeiCuz6",
  socials: {
    linkedin: "https://www.linkedin.com/in/fujacob/",
    github: "https://github.com/fujacob/",
    twitter: "https://x.com/fujacobb/",
    email: "jjacobfu@gmail.com",
  },
};

export const experiences: ExperienceCard[] = [
  {
    id: "exp-hubspot-2",
    type: "experience",
    section: "experiences",
    company: "HubSpot",
    logo: "/companies/hubspot.png",
    role: "Software Engineering Intern",
    period: "Jan 2026 - Present",
    description: "Incoming intern",
    bullets: ["Starting January 2026"],
    colors: { light: "#ffedd5", dark: "#ea580c" },
  },
  {
    id: "exp-kaimz",
    type: "experience",
    section: "experiences",
    company: "Kaimz Inc",
    logo: "/companies/kaimz.png",
    role: "Software Developer",
    period: "Sep 2024 - Dec 2024",
    description: "Worked on monitoring agent infrastructure",
    bullets: ["Built monitoring agent systems", "Infrastructure development"],
    colors: { light: "#ede9fe", dark: "#7c3aed" },
  },
  {
    id: "exp-hubspot-1",
    type: "experience",
    section: "experiences",
    company: "HubSpot",
    logo: "/companies/hubspot.png",
    role: "Software Engineering Intern",
    period: "May 2024 - Aug 2024",
    description: "Shipped features for sales workspace",
    bullets: [
      "Developed sales workspace features",
      "Collaborated with cross-functional teams",
    ],
    colors: { light: "#ffedd5", dark: "#ea580c" },
  },
  {
    id: "exp-bridgewell",
    type: "experience",
    section: "experiences",
    company: "Bridgewell Financial",
    logo: "/companies/bridgewell.png",
    role: "Full Stack Developer",
    period: "Jan 2024 - Apr 2024",
    description: "Built in-house client onboarding portal",
    bullets: [
      "Developed client onboarding portal from scratch",
      "Full-stack development",
    ],
    colors: { light: "#e0f2fe", dark: "#0284c7" },
  },
  {
    id: "exp-weehooey",
    type: "experience",
    section: "experiences",
    company: "Weehooey Inc",
    logo: "/companies/weehooey.png",
    role: "Software Developer",
    period: "May 2023 - Aug 2023",
    description: "Developed client tooling",
    bullets: ["Built internal client tools", "Improved developer workflows"],
    colors: { light: "#dcfce7", dark: "#16a34a" },
  },
];

export const projects: ProjectCard[] = [
  {
    id: "proj-rbveal",
    type: "project",
    section: "projects",
    title: "RBveal",
    image: "/projects/rbveal.png",
    description: "Multi-Stage Phishing Simulator",
    award: "UofTHacks Winner – RBC 1st Place Prize ($1,000)",
    technologies: ["Next.js", "React", "WebSockets", "OpenAI", "Twilio"],
    bullets: [
      "Dynamic email generation with AI",
      "Banking interface simulations",
      "AI-powered call agents",
    ],
    githubUrl: "https://github.com/FuJacob/rbveal",
    colors: { light: "#f3e8ff", dark: "#9333ea" },
  },
  {
    id: "proj-fairfi",
    type: "project",
    section: "projects",
    title: "FairFi",
    image: "/projects/fairfi.jpg",
    description: "Bias Detection for Call-Agents",
    award: "DeltaHacks Winner – P&G 1st Place ($750)",
    technologies: ["Next.js", "React", "Twilio", "Cohere", "MongoDB"],
    bullets: [
      "Real-time bias analysis",
      "Financial service employee monitoring",
    ],
    githubUrl: "https://github.com/fujacob/fairfi",
    colors: { light: "#ffedd5", dark: "#ea580c" },
  },
  {
    id: "proj-leetdance",
    type: "project",
    section: "projects",
    title: "LeetDance",
    image: "/projects/leetdance.png",
    description: "LeetCode For TikTok Dances",
    technologies: ["Next.js", "FastAPI", "OpenCV", "MongoDB"],
    bullets: [
      "Full-stack dance challenges platform",
      "Real-time feedback with MediaPipe",
    ],
    githubUrl: "https://github.com/FuJacob/leetdance",
    colors: { light: "#fce7f3", dark: "#db2777" },
  },
  {
    id: "proj-metroapocalypse",
    type: "project",
    section: "projects",
    title: "Metro Apocalypse",
    image: "/projects/metroapocalypse.png",
    description: "Zombie Tag .IO Game",
    award: "248k+ users, $2,500+ CAD revenue",
    technologies: ["HTML5", "JavaScript", "Modd.io"],
    bullets: [
      "Multiplayer HTML5 .io game",
      "In-game microtransactions",
    ],
    liveUrl: "https://www.patreon.com/amuletio",
    colors: { light: "#ecfccb", dark: "#65a30d" },
  },
];

export const walletSections: WalletSection[] = [
  { id: "about", label: "About", cards: [aboutCard] },
  { id: "experiences", label: "Experience", cards: experiences },
  { id: "projects", label: "Projects", cards: projects },
];
